services:
  - type: web
    name: stock-analyze
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn stock_analyze_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stock_analyze_project.settings
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        value: your_database_url
